jobs:
  include:
    - stage: Build
      script: echo "Testing build..."
      script: echo "Test" > test.txt
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases..."
      deploy:
        provider: releases
        #api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file:
          - test.txt
        on:
          tags: true
