jobs:
  include:
    - stage: Build
      script: echo "Testing build..."
      script: echo "Test" > test.txt
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases..."
      before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Finchiedev"
      - git config --local user.email "developer.finchie@gmail.com"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        #api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file:
          - test.txt
        draft: true
